// playlist.js
// Lista de musicas do player. Cada faixa aponta para o mp3 em assets/audio/
// e para o bloco (imagem) correspondente em assets/images/blocks/.
//
export const playlist = [
  {
    id: "anavitoria-ai-amor",
    title: "Ai, Amor",
    artist: "ANAVITÓRIA",
    file: "assets/audio/anavitoria-ai-amor.mp3",
    block: "assets/images/blocks/anavitoria-ai-amor.png",
  },
  {
    id: "anavitoria-cor-de-marte",
    title: "Cor de Marte",
    artist: "ANAVITÓRIA",
    file: "assets/audio/anavitoria-cor-de-marte.mp3",
    block: "assets/images/blocks/anavitoria-cor-de-marte.png",
  },
  {
    id: "anavitoria-dengo",
    title: "Dengo",
    artist: "ANAVITÓRIA",
    file: "assets/audio/anavitoria-dengo.mp3",
    block: "assets/images/blocks/anavitoria-dengo.png",
  },
  {
    id: "anavitoria-explodir-ao-vivo",
    title: "Explodir (Ao Vivo)",
    artist: "ANAVITÓRIA",
    file: "assets/audio/anavitoria-explodir-ao-vivo.mp3",
    block: "assets/images/blocks/anavitoria-explodir-ao-vivo.png",
  },
  {
    id: "anavitoria-ter-o-coracao-no-chao",
    title: "Ter o Coração no Chão",
    artist: "ANAVITÓRIA",
    file: "assets/audio/anavitoria-ter-o-coracao-no-chao.mp3",
    block: "assets/images/blocks/anavitoria-ter-o-coracao-no-chao.png",
  },
  {
    id: "cigarettes-after-sex-apocalypse",
    title: "Apocalypse",
    artist: "Cigarettes After Sex",
    file: "assets/audio/cigarettes-after-sex-apocalypse.mp3",
    block: "assets/images/blocks/cigarettes-after-sex-apocalypse.png",
  },
  {
    id: "bruno-major-nothing",
    title: "Nothing",
    artist: "Bruno Major",
    file: "assets/audio/bruno-major-nothing.mp3",
    block: "assets/images/blocks/bruno-major-nothing.png",
  },
  {
    id: "bruno-major-the-most-beautiful-thing",
    title: "The Most Beautiful Thing",
    artist: "Bruno Major",
    file: "assets/audio/bruno-major-the-most-beautiful-thing.mp3",
    block: "assets/images/blocks/bruno-major-the-most-beautiful-thing.png",
  },
  {
    id: "bts-dimple",
    title: "Dimple",
    artist: "BTS",
    file: "assets/audio/bts-dimple.mp3",
    block: "assets/images/blocks/bts-dimple.png",
  },
  {
    id: "damiano-david-the-first-time",
    title: "The First Time",
    artist: "Damiano David",
    file: "assets/audio/damiano-david-the-first-time.mp3",
    block: "assets/images/blocks/damiano-david-the-first-time.png",
  },
  {
    id: "daniel-caesar-ft-h-e-r-best-part",
    title: "Best Part",
    artist: "Daniel Caesar ft. H.E.R.",
    file: "assets/audio/daniel-caesar-ft-h-e-r-best-part.mp3",
    block: "assets/images/blocks/daniel-caesar-ft-h-e-r-best-part.png",
  },
  {
    id: "daniel-caesar-superpowers",
    title: "Superpowers",
    artist: "Daniel Caesar",
    file: "assets/audio/daniel-caesar-superpowers.mp3",
    block: "assets/images/blocks/daniel-caesar-superpowers.png",
  },
  {
    id: "dermot-kennedy-power-over-me",
    title: "Power Over Me",
    artist: "Dermot Kennedy",
    file: "assets/audio/dermot-kennedy-power-over-me.mp3",
    block: "assets/images/blocks/dermot-kennedy-power-over-me.png",
  },
  {
    id: "enhypen-polaroid-love-live",
    title: "Polaroid Love (Live)",
    artist: "ENHYPEN",
    file: "assets/audio/enhypen-polaroid-love-live.mp3",
    block: "assets/images/blocks/enhypen-polaroid-love-live.png",
  },
  {
    id: "exo-just-as-usual",
    title: "Just As Usual",
    artist: "EXO",
    file: "assets/audio/exo-just-as-usual.mp3",
    block: "assets/images/blocks/exo-just-as-usual.png",
  },
  {
    id: "fujii-kaze-shinunoga-e-wa",
    title: "Shinunoga E-Wa",
    artist: "Fujii Kaze",
    file: "assets/audio/fujii-kaze-shinunoga-e-wa.mp3",
    block: "assets/images/blocks/fujii-kaze-shinunoga-e-wa.png",
  },
  {
    id: "hozier-take-me-to-church",
    title: "Take Me to Church",
    artist: "Hozier",
    file: "assets/audio/hozier-take-me-to-church.mp3",
    block: "assets/images/blocks/hozier-take-me-to-church.png",
  },
  {
    id: "dpr-live-jasmine",
    title: "Jasmine",
    artist: "DPR Live",
    file: "assets/audio/dpr-live-jasmine.mp3",
    block: "assets/images/blocks/dpr-live-jasmine.png",
  },
  {
    id: "justin-bieber-2-much",
    title: "2 Much",
    artist: "Justin Bieber",
    file: "assets/audio/justin-bieber-2-much.mp3",
    block: "assets/images/blocks/justin-bieber-2-much.png",
  },
  {
    id: "justin-bieber-off-my-face",
    title: "Off My Face",
    artist: "Justin Bieber",
    file: "assets/audio/justin-bieber-off-my-face.mp3",
    block: "assets/images/blocks/justin-bieber-off-my-face.png",
  },
  {
    id: "justin-bieber-ft-khalid-as-i-am",
    title: "As I Am",
    artist: "Justin Bieber ft. Khalid",
    file: "assets/audio/justin-bieber-ft-khalid-as-i-am.mp3",
    block: "assets/images/blocks/justin-bieber-ft-khalid-as-i-am.png",
  },
  {
    id: "justin-timberlake-mirrors",
    title: "Mirrors",
    artist: "Justin Timberlake",
    file: "assets/audio/justin-timberlake-mirrors.mp3",
    block: "assets/images/blocks/justin-timberlake-mirrors.png",
  },
  {
    id: "nct-my-everything",
    title: "My Everything",
    artist: "NCT",
    file: "assets/audio/nct-my-everything.mp3",
    block: "assets/images/blocks/nct-my-everything.png",
  },
  {
    id: "new-west-those-eyes-home-session",
    title: "Those Eyes (Home Session)",
    artist: "New West",
    file: "assets/audio/new-west-those-eyes-home-session.mp3",
    block: "assets/images/blocks/new-west-those-eyes-home-session.png",
  },
  {
    id: "exo-no-makeup",
    title: "No Makeup",
    artist: "EXO",
    file: "assets/audio/exo-no-makeup.mp3",
    block: "assets/images/blocks/exo-no-makeup.png",
  },
  {
    id: "one-direction-little-things",
    title: "Little Things",
    artist: "One Direction",
    file: "assets/audio/one-direction-little-things.mp3",
    block: "assets/images/blocks/one-direction-little-things.png",
  },
  {
    id: "roberta-campos-e-nando-reis-de-janeiro-a-janeiro",
    title: "De Janeiro a Janeiro",
    artist: "Roberta Campos e Nando Reis",
    file: "assets/audio/roberta-campos-e-nando-reis-de-janeiro-a-janeiro.mp3",
    block: "assets/images/blocks/roberta-campos-e-nando-reis-de-janeiro-a-janeiro.png",
  },
  {
    id: "rubel-quando-bate-aquela-saudade",
    title: "Quando Bate Aquela Saudade",
    artist: "Rubel",
    file: "assets/audio/rubel-quando-bate-aquela-saudade.mp3",
    block: "assets/images/blocks/rubel-quando-bate-aquela-saudade.png",
  },
  {
    id: "stray-kids-lose-my-breath-live",
    title: "Lose My Breath (Live)",
    artist: "Stray Kids",
    file: "assets/audio/stray-kids-lose-my-breath-live.mp3",
    block: "assets/images/blocks/stray-kids-lose-my-breath-live.png",
  },
  {
    id: "ten-stunner",
    title: "Stunner",
    artist: "TEN",
    file: "assets/audio/ten-stunner.mp3",
    block: "assets/images/blocks/ten-stunner.png",
  },
  {
    id: "enrolados-trilha-sonora-original-vejo-enfim-a-luz-brilhar",
    title: "Vejo Enfim a Luz Brilhar",
    artist: "Enrolados (Trilha Sonora Original)",
    file: "assets/audio/enrolados-trilha-sonora-original-vejo-enfim-a-luz-brilhar.mp3",
    block: "assets/images/blocks/enrolados-trilha-sonora-original-vejo-enfim-a-luz-brilhar.png",
  },
  {
    id: "michael-jackson-you-are-not-alone",
    title: "You Are Not Alone",
    artist: "Michael Jackson",
    file: "assets/audio/michael-jackson-you-are-not-alone.mp3",
    block: "assets/images/blocks/michael-jackson-you-are-not-alone.png",
  },
  {
    id: "ze-neto-e-cristiano-barulho-do-foguete",
    title: "Barulho do Foguete",
    artist: "Zé Neto e Cristiano",
    file: "assets/audio/ze-neto-e-cristiano-barulho-do-foguete.mp3",
    block: "assets/images/blocks/ze-neto-e-cristiano-barulho-do-foguete.png",
  },
];